---
- name: Create an apache config file for site
  template:
    src: alias.conf.j2
    dest: "{{ item.apache.conf_file }}"
  with_items: drupal_sites
  no_log: True
  notify: apache_restart

- name: Overwrite apache config file for site if template exists
  copy:
    content: "{{ item.apache.conf_data }}"
    dest: "{{ item.apache.conf_file }}"
  when: item.apache.conf_data is defined
  with_items: drupal_sites
  no_log: True
  notify: apache_restart

- name: Activate VHost
  command: a2ensite {{ item.apache.conf_file }}
  when: item.apache.mode == "vhost"
  with_items: drupal_sites
  no_log: True
  notify: apache_restart
