---
- name: Create mysql database
  mysql_db:
    config_file: "{{ mysql_defaults_extra_file }}"
    name: "{{ drupal_site_db.name }}"
    state: present

- name: Create mysql user for site
  mysql_user:
    name: "{{ drupal_site_db.username }}"
    password: "{{ drupal_site_db.password }}"
    priv: "{{ drupal_site_db.name }}.*:ALL"
    state: present
    config_file: "{{ mysql_defaults_extra_file }}"
