---
- name: Create mysql database
  mysql_db:
    config_file: "{{ drupal_site_db.conf }}"
    name: "{{ drupal_site_db.name }}"
    encoding: "{{ drupal_site_db.charset }}"
    collation: "{{ drupal_site_db.collate }}"
    state: present

- name: Create mysql user for site
  mysql_user:
    name: "{{ drupal_site_db.name }}"
    password: "{{ drupal_site_db.pass }}"
    priv: "{{ drupal_site_db.name }}.*:ALL"
    state: present
    config_file: "{{ drupal_site_db.conf }}"
