--- 
- Clone the repository
  become: no
  git:
    repo: "{{ drupal_git_site_repo }}"
    dest: "{{ drupal_site_path }} "
    update: yes
  notify: site update permissions

- Install Core Dependencies
  become: no
  composer:
    command: update
    working_dir: "{{ drupal_site_path }}"
