--- 
- name: Clone the repository
  become: yes
  git:
    repo: "{{ drupal_git_site_repo }}"
    dest: "{{ drupal_site_path }}"
    update: yes
  notify: drupal_site update permissions

- name: Install Core Dependencies
  become: yes
  composer:
    command: update
    working_dir: "{{ drupal_site_path }}"
