---
- name: Update services file permissions
  file:
    path: "{{ item.site_path }}/web/sites/default/services.yml"
    mode: 0644
  with_items: drupal_sites
  no_log: True

- name: Update settings file permissions
  file:
    path: "{{ item.site_path }}/web/sites/default/settings.php"
    mode: 0644
  with_items: drupal_sites
  no_log: True

- name: Update Trusted Host Configuration in settings.php
  blockinfile:
    dest: "{{ item.site_path }}/web/sites/default/settings.php"
    block: |
      $settings['trusted_host_patterns'] = [
        '^localhost$',
        '^{{ ansible_host }}$',
      ];
  with_items: drupal_sites
  no_log: True
